// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Troupon.Catalog.Infra.Persistence;

namespace Troupon.Catalog.Service.Api.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20210329200645_addedImage")]
    partial class addedImage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Troupon.Catalog.Core.Domain.Entities.DealEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("Deals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d53c6ce-6181-42a8-8616-03f86f883112"),
                            Description = "0",
                            Details = "1",
                            MerchantId = new Guid("5e448b39-db5b-42a4-bc12-52f34dcd5c14"),
                            Name = "0"
                        },
                        new
                        {
                            Id = new Guid("189014f9-8e78-474f-96b7-d133ffd86d20"),
                            Description = "1",
                            Details = "0",
                            MerchantId = new Guid("5e448b39-db5b-42a4-bc12-52f34dcd5c14"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("ef058c71-3f17-4dc2-aa9d-89c7d5b045e1"),
                            Description = "2",
                            Details = "0",
                            MerchantId = new Guid("5e448b39-db5b-42a4-bc12-52f34dcd5c14"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("7677b632-718f-4b82-9a0f-105adebca394"),
                            Description = "3",
                            Details = "0",
                            MerchantId = new Guid("5e448b39-db5b-42a4-bc12-52f34dcd5c14"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("4549f44e-18e1-468d-9101-fd17db1f5e8f"),
                            Description = "4",
                            Details = "0",
                            MerchantId = new Guid("532e8ec2-121d-4a86-bfe2-8812c2c27232"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("71c72db9-02ef-4e6b-88ad-88f8295b4eba"),
                            Description = "5",
                            Details = "0",
                            MerchantId = new Guid("532e8ec2-121d-4a86-bfe2-8812c2c27232"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("b569c247-d272-4a21-b7e7-341049596af5"),
                            Description = "6",
                            Details = "0",
                            MerchantId = new Guid("83c1dce6-97d5-4a35-afb7-4eb86577160c"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("ed66bc3d-0197-43b5-9648-e20af689d12e"),
                            Description = "7",
                            Details = "1",
                            MerchantId = new Guid("83c1dce6-97d5-4a35-afb7-4eb86577160c"),
                            Name = "1"
                        });
                });

            modelBuilder.Entity("Troupon.Catalog.Core.Domain.Entities.MerchantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e448b39-db5b-42a4-bc12-52f34dcd5c14"),
                            ImageUri = "https://picsum.photos/id/1023/200/300",
                            Name = "Awsome Goods Plus"
                        },
                        new
                        {
                            Id = new Guid("532e8ec2-121d-4a86-bfe2-8812c2c27232"),
                            ImageUri = "https://picsum.photos/id/1003/200/300",
                            Name = "Masso Relax Inc"
                        },
                        new
                        {
                            Id = new Guid("83c1dce6-97d5-4a35-afb7-4eb86577160c"),
                            ImageUri = "https://picsum.photos/id/1012/200/300",
                            Name = "Antirouille la magouille"
                        },
                        new
                        {
                            Id = new Guid("042038de-1e60-427d-bdce-7d683ffc8bf5"),
                            ImageUri = "https://picsum.photos/id/1011/200/300",
                            Name = "Bronsage & Debosselage Reuni"
                        });
                });

            modelBuilder.Entity("Troupon.Catalog.Core.Domain.Entities.DealEntity", b =>
                {
                    b.HasOne("Troupon.Catalog.Core.Domain.Entities.MerchantEntity", "Merchant")
                        .WithMany("Deals")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Troupon.Catalog.Core.Domain.Entities.MerchantEntity", b =>
                {
                    b.Navigation("Deals");
                });
#pragma warning restore 612, 618
        }
    }
}
