// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Troupon.Catalog.Infra.Persistence;

namespace Troupon.Catalog.Service.Api.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Troupon.Catalog.Core.Domain.Entities.DealEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("Deals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d53c6ce-6181-42a8-8616-03f86f883112"),
                            Description = "0",
                            Details = "1",
                            MerchantId = new Guid("5e448b39-db5b-42a4-bc12-52f34dcd5c14"),
                            Name = "0"
                        },
                        new
                        {
                            Id = new Guid("f6faaf05-4e4d-4beb-b13d-d3d4d8522c24"),
                            Description = "1",
                            Details = "0",
                            MerchantId = new Guid("5e448b39-db5b-42a4-bc12-52f34dcd5c14"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("1edf029a-49d5-481b-8abc-82fb2984a935"),
                            Description = "2",
                            Details = "0",
                            MerchantId = new Guid("5e448b39-db5b-42a4-bc12-52f34dcd5c14"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("c02fdfbc-5376-4e27-a1e4-5fb41169be80"),
                            Description = "3",
                            Details = "0",
                            MerchantId = new Guid("5e448b39-db5b-42a4-bc12-52f34dcd5c14"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("bf636b10-73ab-4ac9-9b49-3cc7edc32fbf"),
                            Description = "4",
                            Details = "0",
                            MerchantId = new Guid("532e8ec2-121d-4a86-bfe2-8812c2c27232"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("658383fd-fa67-4324-825c-287a754713f6"),
                            Description = "5",
                            Details = "0",
                            MerchantId = new Guid("532e8ec2-121d-4a86-bfe2-8812c2c27232"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("2492f690-1a77-4cc1-8234-827338976189"),
                            Description = "6",
                            Details = "0",
                            MerchantId = new Guid("83c1dce6-97d5-4a35-afb7-4eb86577160c"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("309a8ad5-5d37-4b09-a918-8832ddf20721"),
                            Description = "7",
                            Details = "1",
                            MerchantId = new Guid("83c1dce6-97d5-4a35-afb7-4eb86577160c"),
                            Name = "1"
                        });
                });

            modelBuilder.Entity("Troupon.Catalog.Core.Domain.Entities.MerchantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e448b39-db5b-42a4-bc12-52f34dcd5c14"),
                            ImageUri = "https://picsum.photos/id/1023/200/300",
                            Name = "Awsome Goods Plus"
                        },
                        new
                        {
                            Id = new Guid("532e8ec2-121d-4a86-bfe2-8812c2c27232"),
                            ImageUri = "https://picsum.photos/id/1003/200/300",
                            Name = "Masso Relax Inc"
                        },
                        new
                        {
                            Id = new Guid("83c1dce6-97d5-4a35-afb7-4eb86577160c"),
                            ImageUri = "https://picsum.photos/id/1012/200/300",
                            Name = "Antirouille la magouille"
                        },
                        new
                        {
                            Id = new Guid("042038de-1e60-427d-bdce-7d683ffc8bf5"),
                            ImageUri = "https://picsum.photos/id/1011/200/300",
                            Name = "Bronsage & Debosselage Reuni"
                        });
                });

            modelBuilder.Entity("Troupon.Catalog.Core.Domain.Entities.DealEntity", b =>
                {
                    b.HasOne("Troupon.Catalog.Core.Domain.Entities.MerchantEntity", "Merchant")
                        .WithMany("Deals")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Troupon.Catalog.Core.Domain.Entities.MerchantEntity", b =>
                {
                    b.Navigation("Deals");
                });
#pragma warning restore 612, 618
        }
    }
}
