// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Troupon.Catalog.Infra.Persistence;

namespace Troupon.Catalog.Service.Api.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Troupon.Catalog.Infra.Persistence.Entities.ApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cdd0807a-0c78-469e-8da9-8cd7e3d03862"),
                            Name = "AGATE"
                        },
                        new
                        {
                            Id = new Guid("f60631e1-180d-4ff6-96b8-9ccd087ef6dc"),
                            Name = "ADP"
                        },
                        new
                        {
                            Id = new Guid("911d50da-f83b-4823-9e08-3d51bfd2808f"),
                            Name = "Facturation"
                        });
                });

            modelBuilder.Entity("Troupon.Catalog.Infra.Persistence.Entities.DealEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Minor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Deals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d53c6ce-6181-42a8-8616-03f86f883112"),
                            Major = "0",
                            Minor = "0",
                            Patch = "1"
                        },
                        new
                        {
                            Id = new Guid("29c0efb7-66e1-4e3e-acda-c76b093fba39"),
                            Major = "1",
                            Minor = "1",
                            Patch = "0"
                        },
                        new
                        {
                            Id = new Guid("1287acfb-896a-4f74-9625-902e896eae8d"),
                            Major = "1",
                            Minor = "2",
                            Patch = "0"
                        },
                        new
                        {
                            Id = new Guid("801f494f-6dd0-4e31-bced-0edb1de1d935"),
                            Major = "1",
                            Minor = "3",
                            Patch = "0"
                        },
                        new
                        {
                            Id = new Guid("791fb17d-1940-4ea6-8fa2-08270c7ff664"),
                            Major = "1",
                            Minor = "4",
                            Patch = "0"
                        },
                        new
                        {
                            Id = new Guid("f6f46956-72d9-4d78-b1c1-17aaadf35d84"),
                            Major = "1",
                            Minor = "5",
                            Patch = "0"
                        },
                        new
                        {
                            Id = new Guid("aade210f-7fbf-4716-84ea-f45841f95f91"),
                            Major = "1",
                            Minor = "6",
                            Patch = "0"
                        },
                        new
                        {
                            Id = new Guid("331fa952-5e0b-451d-8f20-e3a65ec8ff03"),
                            Major = "1",
                            Minor = "7",
                            Patch = "1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
